[2023-05-26T20:08:55.113+0700] {processor.py:157} INFO - Started process (PID=4373) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:08:55.114+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:08:55.114+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:08:55.114+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:08:55.115+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:08:55.116+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:08:55.115+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:08:55.116+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:08:55.140+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.029 seconds
[2023-05-26T20:09:25.668+0700] {processor.py:157} INFO - Started process (PID=4763) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:09:25.669+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:09:25.669+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:09:25.669+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:09:25.671+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:09:25.672+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:09:25.672+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:09:25.673+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:09:25.689+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.023 seconds
[2023-05-26T20:09:56.508+0700] {processor.py:157} INFO - Started process (PID=4956) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:09:56.509+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:09:56.509+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:09:56.509+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:09:56.510+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:09:56.511+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:09:56.510+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:09:56.511+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:09:56.524+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.018 seconds
[2023-05-26T20:10:26.749+0700] {processor.py:157} INFO - Started process (PID=5158) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:10:26.750+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:10:26.750+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:10:26.750+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:10:26.751+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:10:26.752+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:10:26.751+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:10:26.752+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:10:26.764+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.017 seconds
[2023-05-26T20:10:56.862+0700] {processor.py:157} INFO - Started process (PID=5339) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:10:56.863+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:10:56.864+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:10:56.864+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:10:56.866+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:10:56.869+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:10:56.867+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:10:56.869+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:10:56.893+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.035 seconds
[2023-05-26T20:11:27.811+0700] {processor.py:157} INFO - Started process (PID=5645) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:11:27.812+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:11:27.812+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:11:27.812+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:11:27.814+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:11:27.814+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:11:27.814+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:11:27.815+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:11:27.829+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.019 seconds
[2023-05-26T20:11:57.972+0700] {processor.py:157} INFO - Started process (PID=5895) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:11:57.972+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:11:57.973+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:11:57.973+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:11:57.974+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:11:57.975+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:11:57.974+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:11:57.975+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:11:57.987+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.017 seconds
[2023-05-26T20:12:28.113+0700] {processor.py:157} INFO - Started process (PID=6189) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:12:28.113+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:12:28.114+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:12:28.113+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:12:28.115+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:12:28.115+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:12:28.115+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:12:28.115+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:12:28.128+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.017 seconds
[2023-05-26T20:12:58.188+0700] {processor.py:157} INFO - Started process (PID=6357) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:12:58.188+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:12:58.189+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:12:58.189+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:12:58.190+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:12:58.191+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:12:58.190+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:12:58.191+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:12:58.204+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.018 seconds
[2023-05-26T20:13:28.404+0700] {processor.py:157} INFO - Started process (PID=6535) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:13:28.405+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:13:28.405+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:13:28.405+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:13:28.406+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:13:28.407+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:13:28.406+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:13:28.407+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:13:28.420+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.017 seconds
[2023-05-26T20:13:58.568+0700] {processor.py:157} INFO - Started process (PID=6715) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:13:58.568+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:13:58.569+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:13:58.568+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:13:58.570+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:13:58.571+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:13:58.570+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:13:58.571+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:13:58.585+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.019 seconds
[2023-05-26T20:14:28.816+0700] {processor.py:157} INFO - Started process (PID=6897) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:14:28.817+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:14:28.818+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:14:28.818+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:14:28.819+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:14:28.820+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:14:28.819+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:14:28.820+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:14:28.852+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.038 seconds
[2023-05-26T20:14:59.202+0700] {processor.py:157} INFO - Started process (PID=7112) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:14:59.203+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:14:59.203+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:14:59.203+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:14:59.205+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:14:59.205+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:14:59.205+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:14:59.206+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:14:59.222+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.021 seconds
[2023-05-26T20:15:29.712+0700] {processor.py:157} INFO - Started process (PID=7374) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:15:29.713+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:15:29.713+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:15:29.713+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:15:29.714+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:15:29.715+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:15:29.714+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:15:29.715+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:15:29.728+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.018 seconds
[2023-05-26T20:16:00.172+0700] {processor.py:157} INFO - Started process (PID=7592) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:16:00.173+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:16:00.173+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:16:00.173+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:16:00.174+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:16:00.175+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:16:00.174+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:16:00.175+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:16:00.188+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.018 seconds
[2023-05-26T20:16:30.489+0700] {processor.py:157} INFO - Started process (PID=7767) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:16:30.490+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:16:30.490+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:16:30.490+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:16:30.492+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:16:30.492+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:16:30.492+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:16:30.493+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:16:30.508+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.020 seconds
[2023-05-26T20:17:00.821+0700] {processor.py:157} INFO - Started process (PID=8040) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:17:00.822+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:17:00.822+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:17:00.822+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:17:00.823+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:17:00.824+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:17:00.823+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:17:00.824+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:17:00.838+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.019 seconds
[2023-05-26T20:17:31.035+0700] {processor.py:157} INFO - Started process (PID=8186) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:17:31.035+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:17:31.036+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:17:31.035+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:17:31.037+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:17:31.037+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:17:31.037+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:17:31.038+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:17:31.050+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.017 seconds
[2023-05-26T20:18:01.195+0700] {processor.py:157} INFO - Started process (PID=8335) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:18:01.196+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:18:01.196+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:18:01.196+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:18:01.197+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:18:01.198+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:18:01.197+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:18:01.198+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:18:01.214+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.021 seconds
[2023-05-26T20:18:31.774+0700] {processor.py:157} INFO - Started process (PID=8504) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:18:31.774+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:18:31.774+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:18:31.774+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:18:31.776+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:18:31.776+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:18:31.776+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:18:31.776+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:18:31.789+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.017 seconds
[2023-05-26T20:19:02.117+0700] {processor.py:157} INFO - Started process (PID=8665) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:19:02.118+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:19:02.118+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:19:02.118+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:19:02.119+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:19:02.120+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:19:02.119+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:19:02.120+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:19:02.132+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.017 seconds
[2023-05-26T20:19:32.307+0700] {processor.py:157} INFO - Started process (PID=8850) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:19:32.307+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:19:32.308+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:19:32.308+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:19:32.309+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:19:32.309+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:19:32.309+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:19:32.310+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:19:32.322+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.017 seconds
[2023-05-26T20:20:02.591+0700] {processor.py:157} INFO - Started process (PID=9009) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:20:02.592+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:20:02.593+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:20:02.593+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:20:02.596+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:20:02.597+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:20:02.597+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:20:02.598+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:20:02.626+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.038 seconds
[2023-05-26T20:20:33.184+0700] {processor.py:157} INFO - Started process (PID=9173) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:20:33.185+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:20:33.185+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:20:33.185+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:20:33.186+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:20:33.187+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:20:33.186+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:20:33.187+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:20:33.200+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.017 seconds
[2023-05-26T20:21:03.446+0700] {processor.py:157} INFO - Started process (PID=9340) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:21:03.446+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:21:03.447+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:21:03.447+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:21:03.448+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:21:03.448+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:21:03.448+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:21:03.449+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:21:03.461+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.017 seconds
[2023-05-26T20:21:33.528+0700] {processor.py:157} INFO - Started process (PID=9509) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:21:33.529+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:21:33.529+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:21:33.529+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:21:33.530+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:21:33.531+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:21:33.530+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:21:33.531+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:21:33.543+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.017 seconds
[2023-05-26T20:22:03.655+0700] {processor.py:157} INFO - Started process (PID=9727) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:22:03.655+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:22:03.656+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:22:03.656+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:22:03.657+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:22:03.658+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:22:03.657+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:22:03.658+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:22:03.672+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.019 seconds
[2023-05-26T20:22:33.989+0700] {processor.py:157} INFO - Started process (PID=9931) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:22:33.989+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:22:33.990+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:22:33.990+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:22:33.991+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:22:33.991+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:22:33.991+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:22:33.992+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:22:34.004+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.017 seconds
[2023-05-26T20:23:04.321+0700] {processor.py:157} INFO - Started process (PID=10135) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:23:04.321+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:23:04.322+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:23:04.321+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:23:04.323+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:23:04.323+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:23:04.323+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:23:04.324+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:23:04.337+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.019 seconds
[2023-05-26T20:23:34.569+0700] {processor.py:157} INFO - Started process (PID=10334) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:23:34.570+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:23:34.570+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:23:34.570+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:23:34.571+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:23:34.572+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:23:34.571+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:23:34.572+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:23:34.585+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.018 seconds
[2023-05-26T20:24:04.710+0700] {processor.py:157} INFO - Started process (PID=10518) to work on /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:24:04.710+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/dag2.py for tasks to queue
[2023-05-26T20:24:04.711+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:24:04.710+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:24:04.712+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/dag2_20230525HH.json================
[2023-05-26T20:24:04.712+0700] {logging_mixin.py:149} INFO - [2023-05-26T20:24:04.712+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/dag2.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/dag2.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/dag2_20230525HH.json'
[2023-05-26T20:24:04.712+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/dag2.py
[2023-05-26T20:24:04.727+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/dag2.py took 0.019 seconds
