[2023-05-25T08:59:54.867+0700] {processor.py:157} INFO - Started process (PID=19732) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T08:59:54.868+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T08:59:54.868+0700] {logging_mixin.py:149} INFO - [2023-05-25T08:59:54.868+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T08:59:54.870+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T08:59:54.871+0700] {logging_mixin.py:149} INFO - [2023-05-25T08:59:54.870+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T08:59:54.871+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T08:59:54.884+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.019 seconds
[2023-05-25T09:00:25.296+0700] {processor.py:157} INFO - Started process (PID=19899) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T09:00:25.297+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T09:00:25.298+0700] {logging_mixin.py:149} INFO - [2023-05-25T09:00:25.298+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T09:00:25.301+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T09:00:25.302+0700] {logging_mixin.py:149} INFO - [2023-05-25T09:00:25.301+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T09:00:25.303+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T09:00:25.328+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.038 seconds
[2023-05-25T09:00:55.986+0700] {processor.py:157} INFO - Started process (PID=20045) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T09:00:55.987+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T09:00:55.987+0700] {logging_mixin.py:149} INFO - [2023-05-25T09:00:55.987+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T09:00:55.990+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T09:00:55.991+0700] {logging_mixin.py:149} INFO - [2023-05-25T09:00:55.990+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T09:00:55.992+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T09:00:56.011+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.029 seconds
[2023-05-25T09:01:26.428+0700] {processor.py:157} INFO - Started process (PID=20235) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T09:01:26.429+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T09:01:26.429+0700] {logging_mixin.py:149} INFO - [2023-05-25T09:01:26.429+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T09:01:26.431+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T09:01:26.433+0700] {logging_mixin.py:149} INFO - [2023-05-25T09:01:26.432+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T09:01:26.433+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T09:01:26.525+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.101 seconds
[2023-05-25T09:01:56.877+0700] {processor.py:157} INFO - Started process (PID=20423) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T09:01:56.878+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T09:01:56.879+0700] {logging_mixin.py:149} INFO - [2023-05-25T09:01:56.879+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T09:01:56.881+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T09:01:56.883+0700] {logging_mixin.py:149} INFO - [2023-05-25T09:01:56.882+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T09:01:56.883+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T09:01:56.899+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.026 seconds
[2023-05-25T11:12:41.052+0700] {processor.py:157} INFO - Started process (PID=60769) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:12:41.054+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:12:41.055+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:12:41.055+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:12:41.056+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:12:41.057+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:12:41.056+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:12:41.057+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:12:41.071+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.021 seconds
[2023-05-25T11:13:11.174+0700] {processor.py:157} INFO - Started process (PID=60943) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:13:11.177+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:13:11.179+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:13:11.179+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:13:11.184+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:13:11.187+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:13:11.184+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:13:11.187+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:13:11.226+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.053 seconds
[2023-05-25T11:13:41.461+0700] {processor.py:157} INFO - Started process (PID=61109) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:13:41.463+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:13:41.464+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:13:41.464+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:13:41.468+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:13:41.470+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:13:41.469+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:13:41.471+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:13:41.493+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.040 seconds
[2023-05-25T11:14:11.652+0700] {processor.py:157} INFO - Started process (PID=61290) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:14:11.656+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:14:11.657+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:14:11.657+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:14:11.662+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:14:11.665+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:14:11.662+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:14:11.666+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:14:11.702+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.057 seconds
[2023-05-25T11:14:41.818+0700] {processor.py:157} INFO - Started process (PID=61473) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:14:41.819+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:14:41.819+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:14:41.819+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:14:41.821+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:14:41.822+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:14:41.821+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:14:41.823+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:14:41.843+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.028 seconds
[2023-05-25T11:15:11.967+0700] {processor.py:157} INFO - Started process (PID=61647) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:15:11.967+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:15:11.968+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:15:11.968+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:15:11.969+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:15:11.970+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:15:11.969+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:15:11.970+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:15:11.985+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.026 seconds
[2023-05-25T11:15:42.095+0700] {processor.py:157} INFO - Started process (PID=61815) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:15:42.097+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:15:42.098+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:15:42.098+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:15:42.099+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:15:42.100+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:15:42.099+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:15:42.100+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:15:42.115+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.022 seconds
[2023-05-25T11:16:12.362+0700] {processor.py:157} INFO - Started process (PID=62034) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:16:12.364+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:16:12.364+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:16:12.364+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:16:12.366+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:16:12.366+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:16:12.366+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:16:12.367+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:16:12.380+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.020 seconds
[2023-05-25T11:16:42.484+0700] {processor.py:157} INFO - Started process (PID=62295) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:16:42.487+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:16:42.489+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:16:42.488+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:16:42.493+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:16:42.496+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:16:42.494+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:16:42.497+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:16:42.533+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.056 seconds
[2023-05-25T11:17:12.684+0700] {processor.py:157} INFO - Started process (PID=62469) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:17:12.684+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:17:12.685+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:17:12.685+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:17:12.686+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:17:12.687+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:17:12.686+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:17:12.687+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:17:12.699+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.017 seconds
[2023-05-25T11:17:42.864+0700] {processor.py:157} INFO - Started process (PID=62641) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:17:42.867+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:17:42.867+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:17:42.867+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:17:42.869+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:17:42.870+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:17:42.869+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:17:42.870+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:17:42.884+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.022 seconds
[2023-05-25T11:18:13.188+0700] {processor.py:157} INFO - Started process (PID=62860) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:18:13.191+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:18:13.192+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:18:13.192+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:18:13.196+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:18:13.198+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:18:13.196+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:18:13.198+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:18:13.220+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.036 seconds
[2023-05-25T11:18:43.989+0700] {processor.py:157} INFO - Started process (PID=63067) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:18:43.990+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:18:43.991+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:18:43.991+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:18:43.992+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:18:43.994+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:18:43.993+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:18:43.995+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:18:44.020+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.035 seconds
[2023-05-25T11:19:14.328+0700] {processor.py:157} INFO - Started process (PID=63258) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:19:14.329+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:19:14.329+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:19:14.329+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:19:14.331+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:19:14.332+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:19:14.332+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:19:14.333+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:19:14.348+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.023 seconds
[2023-05-25T11:19:45.151+0700] {processor.py:157} INFO - Started process (PID=63627) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:19:45.152+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:19:45.152+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:19:45.152+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:19:45.153+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:19:45.154+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:19:45.154+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:19:45.154+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:19:45.172+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.023 seconds
[2023-05-25T11:20:15.246+0700] {processor.py:157} INFO - Started process (PID=63839) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:20:15.247+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:20:15.247+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:20:15.247+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:20:15.248+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:20:15.249+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:20:15.249+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:20:15.249+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:20:15.262+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.018 seconds
[2023-05-25T11:20:45.642+0700] {processor.py:157} INFO - Started process (PID=64062) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:20:45.645+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:20:45.646+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:20:45.646+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:20:45.649+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:20:45.650+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:20:45.649+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:20:45.651+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:20:45.666+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.031 seconds
[2023-05-25T11:21:16.010+0700] {processor.py:157} INFO - Started process (PID=64252) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:21:16.014+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:21:16.016+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:21:16.015+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:21:16.020+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:21:16.023+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:21:16.021+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:21:16.024+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:21:16.061+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.058 seconds
[2023-05-25T11:21:46.262+0700] {processor.py:157} INFO - Started process (PID=64444) to work on /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:21:46.265+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_1_20230525.py for tasks to queue
[2023-05-25T11:21:46.266+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:21:46.265+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:21:46.268+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:21:46.271+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:21:46.269+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_1_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_1_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:21:46.271+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_1_20230525.py
[2023-05-25T11:21:46.290+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_1_20230525.py took 0.032 seconds
