[2023-05-25T11:22:42.521+0700] {processor.py:157} INFO - Started process (PID=64871) to work on /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:22:42.522+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_2_20230525.py for tasks to queue
[2023-05-25T11:22:42.523+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:22:42.523+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:22:42.526+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:22:42.527+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:22:42.526+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_2_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_2_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:22:42.528+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:22:42.558+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_2_20230525.py took 0.041 seconds
[2023-05-25T11:23:13.262+0700] {processor.py:157} INFO - Started process (PID=65071) to work on /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:23:13.265+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_2_20230525.py for tasks to queue
[2023-05-25T11:23:13.266+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:23:13.266+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:23:13.269+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:23:13.270+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:23:13.269+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_2_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_2_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:23:13.271+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:23:13.290+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_2_20230525.py took 0.034 seconds
[2023-05-25T11:23:43.443+0700] {processor.py:157} INFO - Started process (PID=65312) to work on /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:23:43.444+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_2_20230525.py for tasks to queue
[2023-05-25T11:23:43.444+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:23:43.444+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:23:43.446+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:23:43.448+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:23:43.447+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_2_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_2_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:23:43.448+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:23:43.464+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_2_20230525.py took 0.025 seconds
[2023-05-25T11:24:13.750+0700] {processor.py:157} INFO - Started process (PID=65503) to work on /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:24:13.753+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_2_20230525.py for tasks to queue
[2023-05-25T11:24:13.753+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:24:13.753+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:24:13.755+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:24:13.755+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:24:13.755+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_2_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_2_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:24:13.756+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:24:13.769+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_2_20230525.py took 0.020 seconds
[2023-05-25T11:24:43.829+0700] {processor.py:157} INFO - Started process (PID=65660) to work on /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:24:43.831+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_2_20230525.py for tasks to queue
[2023-05-25T11:24:43.831+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:24:43.831+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:24:43.833+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:24:43.833+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:24:43.833+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_2_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_2_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:24:43.834+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:24:43.846+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_2_20230525.py took 0.019 seconds
[2023-05-25T11:25:14.769+0700] {processor.py:157} INFO - Started process (PID=65858) to work on /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:25:14.771+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_2_20230525.py for tasks to queue
[2023-05-25T11:25:14.773+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:25:14.772+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:25:14.776+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:25:14.778+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:25:14.776+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_2_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_2_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:25:14.778+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:25:14.798+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_2_20230525.py took 0.035 seconds
[2023-05-25T11:25:45.574+0700] {processor.py:157} INFO - Started process (PID=66039) to work on /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:25:45.577+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_2_20230525.py for tasks to queue
[2023-05-25T11:25:45.578+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:25:45.578+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:25:45.580+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:25:45.581+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:25:45.580+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_2_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_2_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:25:45.581+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:25:45.601+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_2_20230525.py took 0.029 seconds
[2023-05-25T11:26:16.239+0700] {processor.py:157} INFO - Started process (PID=66246) to work on /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:26:16.239+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_2_20230525.py for tasks to queue
[2023-05-25T11:26:16.240+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:26:16.240+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:26:16.242+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:26:16.243+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:26:16.242+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_2_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_2_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:26:16.243+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:26:16.259+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_2_20230525.py took 0.024 seconds
[2023-05-25T11:26:46.870+0700] {processor.py:157} INFO - Started process (PID=66419) to work on /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:26:46.873+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_2_20230525.py for tasks to queue
[2023-05-25T11:26:46.874+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:26:46.874+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:26:46.876+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:26:46.877+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:26:46.876+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_2_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_2_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:26:46.878+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:26:46.900+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_2_20230525.py took 0.033 seconds
[2023-05-25T11:27:17.422+0700] {processor.py:157} INFO - Started process (PID=66648) to work on /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:27:17.425+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_2_20230525.py for tasks to queue
[2023-05-25T11:27:17.426+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:27:17.426+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:27:17.430+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_1_20230525HH.json================
[2023-05-25T11:27:17.432+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:27:17.430+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_2_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_2_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_1_20230525HH.json'
[2023-05-25T11:27:17.433+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:27:17.459+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_2_20230525.py took 0.044 seconds
[2023-05-25T11:32:43.664+0700] {processor.py:157} INFO - Started process (PID=68961) to work on /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:32:43.666+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_2_20230525.py for tasks to queue
[2023-05-25T11:32:43.667+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:32:43.667+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:32:43.669+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_20230525HH.json================
[2023-05-25T11:32:43.669+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:32:43.669+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_2_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_2_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_20230525HH.json'
[2023-05-25T11:32:43.670+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:32:43.683+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_2_20230525.py took 0.021 seconds
[2023-05-25T11:32:47.220+0700] {processor.py:157} INFO - Started process (PID=68996) to work on /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:32:47.220+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_2_20230525.py for tasks to queue
[2023-05-25T11:32:47.221+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:32:47.221+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:32:47.223+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_20230525HH.json================
[2023-05-25T11:32:47.224+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:32:47.223+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_2_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_2_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_20230525HH.json'
[2023-05-25T11:32:47.225+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:32:47.244+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_2_20230525.py took 0.028 seconds
[2023-05-25T11:33:17.415+0700] {processor.py:157} INFO - Started process (PID=69192) to work on /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:33:17.418+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_2_20230525.py for tasks to queue
[2023-05-25T11:33:17.420+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:33:17.419+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:33:17.422+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_20230525HH.json================
[2023-05-25T11:33:17.424+0700] {logging_mixin.py:149} INFO - [2023-05-25T11:33:17.423+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_2_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_2_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_20230525HH.json'
[2023-05-25T11:33:17.424+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_2_20230525.py
[2023-05-25T11:33:17.446+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_2_20230525.py took 0.037 seconds
