[2023-05-25T08:59:54.864+0700] {processor.py:157} INFO - Started process (PID=19731) to work on /home/nhattrieu/airflow/dags/task_7_20230525.py
[2023-05-25T08:59:54.864+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_7_20230525.py for tasks to queue
[2023-05-25T08:59:54.865+0700] {logging_mixin.py:149} INFO - [2023-05-25T08:59:54.865+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_7_20230525.py
[2023-05-25T08:59:54.866+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_5_20230525HH.json================
[2023-05-25T08:59:54.867+0700] {logging_mixin.py:149} INFO - [2023-05-25T08:59:54.866+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_7_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_7_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_5_20230525HH.json'
[2023-05-25T08:59:54.867+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_7_20230525.py
[2023-05-25T08:59:54.883+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_7_20230525.py took 0.021 seconds
[2023-05-25T09:00:25.286+0700] {processor.py:157} INFO - Started process (PID=19898) to work on /home/nhattrieu/airflow/dags/task_7_20230525.py
[2023-05-25T09:00:25.289+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_7_20230525.py for tasks to queue
[2023-05-25T09:00:25.291+0700] {logging_mixin.py:149} INFO - [2023-05-25T09:00:25.291+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_7_20230525.py
[2023-05-25T09:00:25.295+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_5_20230525HH.json================
[2023-05-25T09:00:25.297+0700] {logging_mixin.py:149} INFO - [2023-05-25T09:00:25.296+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_7_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_7_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_5_20230525HH.json'
[2023-05-25T09:00:25.298+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_7_20230525.py
[2023-05-25T09:00:25.326+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_7_20230525.py took 0.047 seconds
[2023-05-25T09:00:55.978+0700] {processor.py:157} INFO - Started process (PID=20044) to work on /home/nhattrieu/airflow/dags/task_7_20230525.py
[2023-05-25T09:00:55.982+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_7_20230525.py for tasks to queue
[2023-05-25T09:00:55.983+0700] {logging_mixin.py:149} INFO - [2023-05-25T09:00:55.983+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_7_20230525.py
[2023-05-25T09:00:55.986+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_5_20230525HH.json================
[2023-05-25T09:00:55.988+0700] {logging_mixin.py:149} INFO - [2023-05-25T09:00:55.986+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_7_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_7_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_5_20230525HH.json'
[2023-05-25T09:00:55.988+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_7_20230525.py
[2023-05-25T09:00:56.010+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_7_20230525.py took 0.039 seconds
[2023-05-25T09:01:26.420+0700] {processor.py:157} INFO - Started process (PID=20234) to work on /home/nhattrieu/airflow/dags/task_7_20230525.py
[2023-05-25T09:01:26.423+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_7_20230525.py for tasks to queue
[2023-05-25T09:01:26.424+0700] {logging_mixin.py:149} INFO - [2023-05-25T09:01:26.424+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_7_20230525.py
[2023-05-25T09:01:26.427+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_5_20230525HH.json================
[2023-05-25T09:01:26.429+0700] {logging_mixin.py:149} INFO - [2023-05-25T09:01:26.428+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_7_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_7_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_5_20230525HH.json'
[2023-05-25T09:01:26.430+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_7_20230525.py
[2023-05-25T09:01:26.522+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_7_20230525.py took 0.109 seconds
[2023-05-25T09:01:56.866+0700] {processor.py:157} INFO - Started process (PID=20422) to work on /home/nhattrieu/airflow/dags/task_7_20230525.py
[2023-05-25T09:01:56.868+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task_7_20230525.py for tasks to queue
[2023-05-25T09:01:56.869+0700] {logging_mixin.py:149} INFO - [2023-05-25T09:01:56.869+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task_7_20230525.py
[2023-05-25T09:01:56.873+0700] {logging_mixin.py:149} INFO - ===============Processing: /json/task_5_20230525HH.json================
[2023-05-25T09:01:56.875+0700] {logging_mixin.py:149} INFO - [2023-05-25T09:01:56.873+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task_7_20230525.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task_7_20230525.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 56, in get_config
    configs = JsonConfigReader.read(self.flow_file_name)
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/json_config_reader.py", line 7, in read
    with open(file_name) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/json/task_5_20230525HH.json'
[2023-05-25T09:01:56.875+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task_7_20230525.py
[2023-05-25T09:01:56.895+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task_7_20230525.py took 0.035 seconds
